### ISSUE TITLE
not working above 6.44 version

### ISSUE THREAD

**Issue by mahendraxceed** [astounding/mtik#14]
I am trying to login above 6.44 version but error sowing invalid username & password

**Comment by juanfrancisco-18** [comment]
I am trying to login above 6.48.6 version but error sowing invalid username & password

**Comment by juanfrancisco-18** [comment]
please ?

**Comment by Lieta2** [comment]
```
./tikcommand <IP> <user> <password> <command>
/disk/sources/mtik/lib/mtik/connection.rb:132:in `login': Login failed: invalid user name or password (6) (MTik::Error)
	from /disk/sources/mtik/lib/mtik/connection.rb:77:in `initialize'
	from /disk/sources/mtik/lib/mtik.rb:266:in `new'
	from /disk/sources/mtik/lib/mtik.rb:266:in `command'
	from ./tikcommand:108:in `<main>'
```
works when using
```
./tikcommand -u <IP> <user> <password> <command>
```
